# Generated by Django 5.0.2 on 2024-05-28 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='category',
            field=models.CharField(choices=[('business', 'Business'), ('world', 'World'), ('health', 'Health'), ('general', 'General')], default='general', max_length=50),
        ),
    ]
