# Generated by Django 5.0.6 on 2024-05-30 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_newsarticle_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='category',
            field=models.CharField(choices=[('business', 'Business'), ('world', 'World'), ('health', 'Health'), ('England', 'England'), ('Asia', 'Asia'), ('Africa', 'Africa'), ('entertainment', 'entertainment'), ('Europe', 'Europe'), ('LatinAmerica', 'LatinAmerica'), ('MiddleEast', 'MiddleEast'), ('NorthernIreland', 'NorthernIreland'), ('Politics', 'Politics'), ('Scotland', 'Scotland'), ('Sports', 'Sports'), ('Technology', 'Technology'), ('UsCanada', 'UsCanada'), ('Wales', 'Wales'), ('general', 'General')], default='general', max_length=50),
        ),
    ]
